#!/usr/bin/env bash
# TeamBrain — monorepo bootstrap (run ONCE inside the freshly created teambrain repo)
set -e
mkdir -p raw/sessions raw/github raw/meetings raw/docs
mkdir -p wiki/concepts wiki/projects wiki/contradictions wiki/people
mkdir -p .teambrain/workflows .teambrain/prompts .github/hooks .github/workflows

touch raw/sessions/.gitkeep raw/github/.gitkeep wiki/concepts/.gitkeep wiki/projects/.gitkeep

[ -f index.md ] || cat > index.md <<'EOF'
# TeamBrain — index
_(regenerated by the indexer; empty until the first ingestion)_
EOF

[ -f log.md ] || printf '# Operations log\n\n' > log.md

[ -f CODEOWNERS ] || cat > CODEOWNERS <<'EOF'
# Adjust with the real members of each project
/wiki/concepts/   @nmlemus
/CLAUDE.md        @nmlemus
# /wiki/projects/project-a/  @dev1 @dev2 @nmlemus
# /wiki/projects/project-b/  @dev3 @dev4 @dev5
EOF

echo "✓ Structure created. Next:"
echo "  1. git add -A && git commit -m 'bootstrap teambrain' && git push"
echo "  2. Grant write access to the team (Settings → Collaborators/Teams)"
echo "  3. In EACH product repo, commit:"
echo "       .github/hooks/teambrain.json      (kit/copilot/teambrain.json)"
echo "       .claude/settings.json             (kit/claude/settings.json, if Claude Code is used)"
echo "       .github/workflows/teambrain.yml   (caller — see top of .github/workflows/resumidor.yml)"
